mysite/forum/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
	url(r'^$', views.home),
	url(r'^login/$', login, {'template_name': 'forum/login.html'}),
	url(r'^logout/$', logout, {'template_name': 'forum/logout.html'}),
	url(r'^register/$', views.register, name='register'),
	url(r'^reg_error/$', views.registerError, name='register'),
	url(r'^addWebsitePost/$', views.addWebsitePost, name='addPost'),
	url(r'^addAssignmentPost/$', views.addAssignmentPost, name='addPost'),
	url(r'^addSurvivingPost/$', views.addSurvivingPost, name='addPost'),
	url(r'^addLectureSlidesPost/$', views.addLectureSlidesPost, name='addPost'),
	url(r'^addChartsPost/$', views.addChartsPost, name='addPost'),
	url(r'^addBinaryPost/$', views.addBinaryPost, name='addPost'),
	url(r'^profile/$', views.viewProfile, name='profile'),
	url(r'^profile/edit/$', views.editProfile, name='editProfile'),
	url(r'^profile/changePassword/$', views.changePassword, name='changePassword'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views

urlpatterns = [
	url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^forum/', include('forum.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

mysite/forum/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length=100, default= '')
	city = models.CharField(max_length = 100, default='')
	website = models.URLField(default='')
	phone = models.IntegerField(default = 0)
	
def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender = User)

class EntryQuerySet(models.QuerySet):
	def published(self):
		return self.filter(publish=True)

class WebsitePost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)

class AssignmentPost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)
        
class SurvivingPost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)

class LectureSlidesPost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)
        
class ChartsPost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)
        
class BinaryPost(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=64)
    body = models.TextField()
 
    def __str__(self):
        return "%s (%s)" % (self.title, self.author)

mysite/forum/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = {
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
		}

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']
			
		if commit:
			user.save()
			
		return user

class PostForm(forms.Form):
	title = forms.CharField(max_length=100)
	body = forms.CharField(max_length=10000)
	
class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'first_name',
			'last_name',
			'password'
			)

mysite/forum/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import login, authenticate, update_session_auth_hash
from forum.forms import RegistrationForm, PostForm, EditProfileForm
from django.views import generic
from . import models
from forum.models import WebsitePost, AssignmentPost, SurvivingPost, LectureSlidesPost, ChartsPost, BinaryPost
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm

def home(request):
	website_posts = WebsitePost.objects.all().order_by('-date')
	assignment_posts = AssignmentPost.objects.all().order_by('-date')
	surviving_posts = SurvivingPost.objects.all().order_by('-date')
	slides_posts = LectureSlidesPost.objects.all().order_by('-date')
	charts_posts = ChartsPost.objects.all().order_by('-date')
	binary_posts = BinaryPost.objects.all().order_by('-date')
	
	args = {'website_posts': website_posts, 
			'assignment_posts': assignment_posts,
			'surviving_posts': surviving_posts,
			'slides_posts': slides_posts,
			'charts_posts': charts_posts,
			'binary_posts': binary_posts,
			}
			
	return render(request, 'forum/home.html', args)
	
def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/forum')
		else:
			return redirect('/forum/reg_error')
	else:
		form = RegistrationForm()

	return render(request, 'forum/reg_form.html')
	
def registerError(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/forum')
	else:
		form = RegistrationForm()

	return render(request, 'forum/reg_error.html')

def addWebsitePost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = WebsitePost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')
	
def addAssignmentPost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = AssignmentPost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')
	
def addSurvivingPost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = SurvivingPost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')
	
def addLectureSlidesPost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = LectureSlidesPost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')
	
def addChartsPost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = ChartsPost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')

def addBinaryPost(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		
		if form.is_valid():
			author = request.user
			title = form.cleaned_data['title']
			body = form.cleaned_data['body']
			
			post = BinaryPost.objects.create(
							title = title,
							author = author,
							body = body)
			return redirect('/forum')
			
	return render(request, 'forum/addPost.html')

def viewProfile(request):
	args = {'user': request.user}
	return render(request, 'forum/profile.html', args)
	
def editProfile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance = request.user)
		
		if form.is_valid():
			form.save()
			return redirect('/forum/profile')
			
	else:
		form = EditProfileForm(instance = request.user)
		args = {'form': form}
		return render(request, 'forum/editProfile.html', args)
		
def changePassword(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user = request.user)
		
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('/forum/profile')
			
		else:
			return redirect('/forum/profile/changePassword')
			
	else:
		form = PasswordChangeForm(user = request.user)
		args = {'form': form}
		return render(request, 'forum/changePassword.html', args)

mysite/forum/templates/forum/addPost.html
{% extends 'base.html' %}

{% block head %}
<title>Entry</title>
{% endblock %}

{% block nav %}
	  <li class="active"><a href="/forum/">Home</a></li>
{% endblock %}

{% block body %}
		<div class="breadcrumbs" style = "background-color: rgba(70,130,180, 0.5)">
			<a href="/forum">Home</a>
&rsaquo; 	<a href="/forum/add">Add Entry</a>
		</div>
    <!-- Content -->
<div id="content" class="colM">
<h1 style = "color: white">Add Forum Post</h1>
<div id="content-main">


<form enctype="multipart/form-data" action="" method="post" id="entry_form" novalidate>
	<input type='hidden' name='csrfmiddlewaretoken' value='HGR6LOSyYAcfqaKTgZTXMY2B9piU1nVh2KIpLGY6QOoHy6swUc9eYFfO5eeWXl3U' />
<div>
  <fieldset class="module aligned ">

        <div class="form-row field-title">
                <div>
                        <label class="required" for="id_title">Title:</label>
                            <input type="text" name="title" id="id_title" required class="vTextField" maxlength="200" style = "color: white"/>
                </div>
        </div>
        <div class="form-row field-body">
                <div>
                        <label class="required" for="id_body">Body:</label>
                        <textarea name="body" id="body" required rows="10" cols="40" class="vLargeTextField" style = "color: white"></textarea>
                </div>
        </div>
</fieldset>
{% csrf_token %}
<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />
</div>
</form>
{% endblock %}

mysite/forum/templates/forum/changePassword.html
{% extends 'base.html' %}

{% block head %}
<title>Change Password</title>

{% endblock %}

<!------------------------------------------------------------>

{% block nav %}
	  <li class="active"><a href="/forum/" style = "color: white;">Home</a></li>
{% endblock %}

{% block body %}

<div class="breadcrumbs" style = "background-color: rgba(70,130,180, 0.5)">
			<a href="/forum">Home</a>
&rsaquo; 	<a href="/forum/profile/edit">Edit Profile</a>
&rsaquo; 	<a href="/forum/add">Change Password</a>
</div>

<div class = "container" style = "color: white">
	<form method = "post">
		<br>
		{% csrf_token %}
			<div style = "float: left; width: 500px; ">
				<p>
					<label for="id_old_password" style = "color: white">Old password:</label> 
					<input type="password" name="old_password" autofocus required id="id_old_password" />
				</p>
				<p>
					<label for="id_new_password1" style = "color: white">New password:</label>
					<input type="password" name="new_password1" required id="id_new_password1" /> 
					<span class="helptext">
						<ul>
							<li>
								Your password can&#39;t be too similar to your other personal information.
							</li>
							<li>
								Your password must contain at least 8 characters.
							</li>
							<li>
								Your password can&#39;t be a commonly used password.
							</li>
							<li>
								Your password can&#39;t be entirely numeric.
							</li>
						</ul>
					</span>
				</p>
				<p>
					<label for="id_new_password2" style = "color: white">New password confirmation:</label> 
					<input type="password" name="new_password2" required id="id_new_password2" />
				</p>
						
			</div>

		<div style = "float: left; width: 800px; margin-top: 30px;  ">
			<button type = "submit">Save changes</button>
		</div>
	</form>
	<br>
</div>
{% endblock %}

mysite/forum/templates/forum/editProfile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>

{% endblock %}

<!------------------------------------------------------------>

{% block nav %}
	  <li class="active"><a href="/forum/" style = "color: white;">Home</a></li>
{% endblock %}

{% block body %}

<div class="breadcrumbs" style = "background-color: rgba(70,130,180, 0.5)">
			<a href="/forum">Home</a>
&rsaquo; 	<a href="/forum/profile">Profile</a>
&rsaquo; 	<a href="/forum/profile/edit">Edit Profile</a>
</div>

<div class = "container" style = "color: white">
	<form method = "post">
		<br>
		{% csrf_token %}
	<div style = "width: 500px; ">
			<div style = "float: left; width: 150px; ">
				<div style = "height: 30px; padding-top: 5px; color: white;">Username:</div>
				
				<div style = "height: 30px;  padding-top: 5px; color: white;">Email:</div>
				
				<div style = "height: 30px;  padding-top: 5px; color: white;">Surname:</div>
				
				<div style = "height: 30px;  padding-top: 5px; color: white;">First Name:</div>
			</div>
			<div style = "float: left; width: 200px; ">
				<div style = "height: 30px;  ">{{ form.username }}</div>
				<div style = "height: 30px;  ">{{ form.email }}</div>
				<div style = "height: 30px; ">{{ form.first_name }}</div>
				<div style = "height: 30px; ">{{ form.last_name }}</div>
<br>
				<a href="/forum/profile/changePassword" style = "color: black; border-bottom: 1px solid black">Change password</a>
			</div>
		</div>

		<div style = "float: left; width: 800px; margin-top: 30px;  ">
			<button type = "submit">Save changes</button>
		</div>
	</form>
	<br>
</div>
{% endblock %}

mysite/forum/templates/forum/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class = "container">
	<form method = "post">
		
		<input type='hidden' name='csrfmiddlewaretoken' value='ZTGS3YsYx69GgKwBHNF38ShwEevABcOKbPj8QplPd5Xe0k1yCUZIM8btD7BFJYP4' />
		<div class = "container" style="text-align:center; width: 100%" >
		<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title" style="font-size: 35px; background-color: rgba(230, 230, 230, 0.4); padding-top: 30px; padding-bottom: 30px; padding-left: 10px; padding-right: 10px; font-style: bold; ">Login to continue</h1>
            <br>
            <div class="account-wall">
                <form class="form-signin">
			<br>
                <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
            <br>
                <input type="password" name="password" class="form-control" placeholder="Password" required>
            <br>
            {% csrf_token %}
                <button style = "color: white" class="btn btn-lg btn-inverse btn-block" type="submit">
                    Sign in
                </button>
        </div>
    </div>
</div>
	</form>
</div>
{% endblock %}

mysite/forum/templates/forum/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logout</title>
{% endblock %}

{% block nav %}
	  <li class="active"><a href="/forum/">Home</a></li>
{% endblock %}

{% block body %}
<div class="container" style="text-align:center">
	<h1>Logged out!</h1>
	<p style>
		You have logged out.
	</p>
</div>
{% endblock %}

mysite/forum/templates/forum/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>

{% endblock %}

<!------------------------------------------------------------>

{% block nav %}
	  <li class="active"><a href="/forum/" style = "color: white;">Home</a></li>
{% endblock %}

{% block body %}

<div class="breadcrumbs" style = "background-color: rgba(70,130,180, 0.5)">
			<a href="/forum">Home</a>
&rsaquo; 	<a href="/forum/add">Profile</a>
</div>

<div id="content" class="colM">
	<h2 style = "color: white; text-indent: 30px; text-align: center; ">
		<B>{{user.first_name}} {{user.last_name}}</B>
	</h2>
	<h4 style = "color: white; text-indent: 30px;">Username: {{user.username}}</h4>
	<h4 style = "color: white; text-indent: 30px;">Email: {{user.email}}</h4>
<div id="content-main">
	
		<ul class="object-tools" style = "padding-top: 10px;">
	<li>
		<a href="/forum/profile/edit" class="addlink">
			Edit Profile
		</a>
   </li>
</ul>
{% endblock %}

mysite/forum/templates/forum/reg_error.html
{% extends 'base.html' %}

{% block head %}
	<title>Registration</title>
{% endblock %}

{% block body %}

<form method = "post">
		{% csrf_token %}
		<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Registration</h3>
			 			</div>
			 			<div class="panel-body">
			    		
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			                <input type="text" name="first_name" id="first_name" class="form-control input-sm floatlabel" placeholder="First Name">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
			    					</div>
			    				</div>
			    			</div>
							<div class="form-group">
			    				<input type="username" name="username" id="username" class="form-control input-sm" placeholder="Username">
			    			</div>
			    			<div class="form-group">
			    				<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password1" id="password1" class="form-control input-sm" placeholder="Password">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password2" id="password2" class="form-control input-sm" placeholder="Confirm Password">
			    					</div>
			    				</div>
			    			</div>
			    			
			    			 <button style = "color: white" class="btn btn-lg btn-inverse btn-block" type="submit">
								Register
							 </button>
							 
								<div class="alert alert-danger" style = "padding-top: 10px; margin-top: 10px; margin-bottom: 1px">
									<strong>Invalid details, please enter again!</strong>
								</div>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>
</form>
{% endblock %}

mysite/forum/templates/forum/reg_form.html
{% extends 'base.html' %}

{% block head %}
	<title>Registration</title>
{% endblock %}

{% block body %}

<form method = "post">
		{% csrf_token %}
	<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Registration</h3>
			 			</div>
			 			<div class="panel-body">
			    		
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			                <input type="text" name="first_name" id="first_name" class="form-control input-sm floatlabel" placeholder="First Name">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
			    					</div>
			    				</div>
			    			</div>
							<div class="form-group">
			    				<input type="username" name="username" id="username" class="form-control input-sm" placeholder="Username">
			    			</div>
			    			<div class="form-group">
			    				<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password1" id="password1" class="form-control input-sm" placeholder="Password">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password2" id="password2" class="form-control input-sm" placeholder="Confirm Password">
			    					</div>
			    				</div>
			    			</div>
			    			<span class="helptext">
						<ul>
							<li>
								Your password can&#39;t be too similar to your other personal information.
							</li>
							<li>
								Your password must contain at least 8 characters.
							</li>
							<li>
								Your password can&#39;t be a commonly used password.
							</li>
							<li>
								Your password can&#39;t be entirely numeric.
							</li>
						</ul>
					</span>
			    			 <button style = "color: white" class="btn btn-lg btn-inverse btn-block" type="submit">
								Register
							 </button>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>
</form>
{% endblock %}